version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      external-github-actions:
          patterns:
              - '*/*'
          exclude-patterns:
              - Tricentis*/*
