name: Check Lint With Stylua
on:
  pull_request:
    paths:
      - "**.lua"
permissions:
  contents: read
  checks: write
  issues: write
  pull-requests: write
jobs:
  format_code:
    runs-on: ubuntu-stepsecurity-x64
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: JohnnyMorganz/stylua-action@479972f01e665acfcba96ada452c36608bdbbb5e # v4.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: .
      - name: suggester
        uses: step-security/action-suggester@854bdfbbb12a23c87d847a6a435eb2e83453407e # v1.24.3
        with:
          tool_name: stylua
          fail_on_error: true
